name: x86-64 Pull and Save Docker Image

on:
  workflow_dispatch:
    inputs:
      docker_images:
        description: '请填写docker镜像名称 多个用英文逗号分开'
        required: true
        default: 'alpine:latest,ubuntu:latest'  # 设置默认的 Docker 镜像列表

jobs:
  pull_and_package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Pull Docker Images and Package
      run: |
        images="${{ github.event.inputs.docker_images }}"
        IFS=',' read -r -a image_array <<< "$images"
        count=0
        images_del=""
        for image in "${image_array[@]}"; do
          docker pull "${image}"
          docker save "${image}" | gzip > "${image//\//_}-amd64.tgz"
          tar -rf x86-64-images.tar.gz *-amd64.tgz
          rm -f *-amd64.tgz
          echo 'rm succ'
          count=$((count+1))
          echo "count-->"${count}
          images_del="${images_del} ${image}"
          if (( count % 10 == 0 )); then
             echo "rmi-->"${images_del}
             docker rmi ${images_del}
             images_del=""
             count=0
          fi
        done

    - name: Compress the TAR files
      run: ls -lh

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: docker-images-tar
        path: x86-64-images.tar.gz
        retention-days: 1  # 将保留天数设置为 1 天 最多可设置90天

    - name: Clean up intermediate files
      run: |
        ls -lh *-amd64.tar.gz
